/* eslint-disable sort-keys */

export const RESUME_FORM_LABELS: Record<string, string> = {
  expandAll: 'Expand all',
  collapseAll: 'Collapse all',
  clear: 'Clear',
  loadTestData: 'Load test data',
  save: 'Save',
  load: 'Load',
  reset: 'Reset',
  submit: 'Submit',
  requiredErrorField: 'This field is required',
  patternErrorField: 'Invalid character on this field',
  savedDataUnavailable: 'Saved data unavailable',
  errorWhileLoadingSavedData: 'Error while loading saved data',
  /* ••[3]••••• Dialogs •••••••••• */
  resetTitle: 'Reset the form',
  resetContent: 'Do you want to reset the form?',
  resetExecuted: 'The form has been reset',
  loadTestDataTitle: 'Load test data onto form',
  loadTestDataContent: 'Do you want to load test data onto the form?',
  loadTestDataExecuted: 'The form has been loaded with test data',
  loadFormTitle: 'Load saved data onto form',
  loadFormContent: 'Do you want to load saved data onto the form?',
  loadFormExecuted: 'The form has been loaded with saved data',
  saveFormTitle: 'Save form data locally',
  saveFormContent: 'Do you want to saved data the form data locally',
  saveFormExecuted: 'The form data has been saved locally',
  /* ••[3]••••• Prices •••••••••• */
  addprice: 'Add Price',
  removeprice: 'Remove Price',
  removePriceTag: 'Remove Price Tag',
  prices: 'Prices',
  price: 'Price',
  priceTag: 'Price Tag',
  priceValue: 'Value',
  priceTitle: 'Price Value',
  priceDescription: 'Price Description',
  /* ••[3]••••• Photos •••••••••• */
  addPhoto: 'Add photo',
  removePhoto: 'Remove photo',
  photos: 'Photos Url',
  photo: 'Photo Url',
};
